#!/bin/sh

name="beta_pdf-symm-view"

latex -ini -interaction=nonstopmode "&latex" \
    "\nonstopmode\nofiles \
    \PassOptionsToPackage{active,tightpage,auctex}{preview} \
    \AtBeginDocument{\
    \ifx\ifPreview\undefined\RequirePackage[displaymath,floats,graphics,textmath,sections,footnotes]{preview}[2004/11/05]\fi}" "\input" ${name}.tex

dvips -Pwww ${name}.dvi -o ${name}-preview.ps

#cat | gs -sOutputFile=%d.png -q -dSAFER -dNOPAUSE -DNOPLATFONTS -dPrinted -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -sDEVICE=png16m -r124.311x123.158 ${name}-preview.ps

#cat | gs -sOutputFile=%d.eps -q -dSAFER -dNOPAUSE -DNOPLATFONTS -dPrinted -dTextAlphaBits=4 -sDEVICE=epswrite -r124.311x123.158 ${name}-preview.ps

#gs -sOutputFile=%d.eps -q -dSAFER -dNOPAUSE -DNOPLATFONTS -sDEVICE=epswrite -r2400 ${name}-preview.ps

gs -sOutputFile=%d.pdf -q -dSAFER -dNOPAUSE -DNOPLATFONTS -sDEVICE=pdfwrite ${name}-preview.ps