#!/bin/sh


# ls *.m | sed '$! s|$|\\|' | sed 's|^|\t|' >> Makefile.am
# (Explanation: list all matlab files (ls *.m), from the output
# replace all end of lines ($) with a backslash (\\) except the last
# line ($!), then prepend all lines (start of line ^) with a tab (\t).)
# Remember to first remove the old stuff before adding  the .m files.


echo "MFILES=\\" > Makefile.inc-mfiles 
#echo "EXTRA_DIST=\\" > Makefile.inc-mfiles 
(ls *.m; ls */*.m) | sed '$! s|$|\\|' | sed 's|^|\t|' >> Makefile.inc-mfiles 
