function cmpsol_large_cmp_simple_pcg

% compares performance between tensor pcg and simple iterations

clc

log_start( fullfile( log_file_base(), mfilename ) );
compare_solvers_pcg( 'model_large_easy', get_solve_options )
show_tex_table(1,[]);
log_stop();

function opts=get_solve_options
opts={};
opts{end+1}=struct( 'longdescr', 'PCG', 'descr', 'PCG', 'type', 'pcg');


opts{end+1}=varargin2options( {...
    'longdescr', 'gpcg', ...
    'descr', 'gpcg',...
    'type', 'gpcg',...
    } );

opts{end+1}=varargin2options( {...
    'longdescr', 'gpcg6', ...
    'descr', 'gpcg6',...
    'type', 'gpcg',...
    'eps', 1e-8
    } );

opts{end+1}=varargin2options( {...
    'longdescr', 'gpcg6 dyn', ...
    'descr', 'gpcg6 dyn',...
    'type', 'gpcg',...
    'dyn', true ...
    'eps', 1e-8 ...
    } );

opts{end+1}=varargin2options( {...
    'longdescr', 'gpcg6 dyn up', ...
    'descr', 'gpcg6 dyn up',...
    'type', 'gpcg',...
    'dyn', true ...
    'eps', 1e-8 ...
    'solve_opts', {'upratio_delta', 0.01, 'dyneps_factor', 0.2} } );

i=2;
for k=1:4
    o=opts{i};
    opts(i+1:end+1)=opts(i:end);

    so=get_option( o, 'solve_opts', {} );
    de=get_option( o, 'descr', '' );
    o.prec_strat={'inside'};
    o.solve_opts=[so, {'beta_formula', 'PR'}];
    o.descr=[de, ' pr'];
    opts{i}=o;
    o.solve_opts=[so, {'beta_formula', 'FR'}];
    o.descr=[de, ' fr'];
    opts{i+1}=o;
    i=i+2;
end
opts([2,3,4,5])=[];

opts{end+1}=varargin2options( {...
    'longdescr', 'gsi', ...
    'descr', 'gsi',...
    'type', 'gsi', ...
    } );

opts{end+1}=varargin2options( {...
    'longdescr', 'gsi dyn', ...
    'descr', 'gsi dyn',...
    'type', 'gsi', ...
    'dyn', true ...
    } );


