function cmpsol_large_op_klterms

% compares performance different numbers of KL terms in the operator

clc

log_start( fullfile( log_file_base(), mfilename ) );
compare_solvers_pcg( 'model_large_easy_lk40', get_solve_options, 'accurate', false )
show_tex_table_2d(1, [], 'hl',[]);
log_stop();

function opts=get_solve_options
%#ok<*AGROW>
opts={};

ilu_options={'type', 'ilutp', 'droptol', 2e-2, 'milu', 'row', 'udiag', 1 };

gsi_std_opts={...
    'descr', 'gsi', ...
    'longdescr', 'gsi', ...
    'solve_opts', {'div_b', 1, 'div_op', 1}, ...
    'eps', 5e-6
    };

gsi_dyn_opts={...
    'descr', 'gsi dyn', ...
    'longdescr', 'gsi dyn', ...
    'solve_opts', {'div_b', 1, 'div_op', 1}, ...
    'dyn', true, ...
    'eps', 1e-8
    };

gsi_ilu_opts={...
    'descr', 'gsi dyn ilu', ...
    'longdescr', 'gsi dyn ilu', ...
    'prec_strat', {'ilu', ilu_options}, ...
    'solve_opts', {'div_b', 10, 'div_op', 10}, ...
    'dyn', true, ...
    'eps', 1e-8, ...
    'check', false
    };



gpcg_std_opts={...
    'descr', 'gpcg', ...
    'longdescr', 'gpcg', ...
    'type', 'gpcg', ...
    'solve_opts', {'div_b', 1, 'div_op', 1}, ...
    'eps', 5e-6};

gpcg_dyn_opts={...
    'descr', 'gpcg dyn', ...
    'longdescr', 'gpcg dyn', ...
    'type', 'gpcg', ...
    'dyn', true, ...
    'eps', 1e-8 };

gpcg_ilu_opts={...
    'descr', 'gpcg dyn/ilu', ...
    'longdescr', 'gpcg dyn/ilu', ...
    'prec_strat', {'ilu', ilu_options}, ...
    'type', 'gpcg', ...
    'dyn', true, ...
    'eps', 1e-8, ...
    'solve_opts', {'div_b', 10, 'div_op', 10}, ...
    };


pcg_mean_opts={...
    'descr', 'pcg', ...
    'longdescr', 'pcg', ...
    'type', 'pcg', ...
    };

pcg_kron_opts={...
    'descr', 'pcg kron', ...
    'longdescr', 'pcg kron', ...
    'type', 'pcg', ...
    'prec', 'kron' };


if fasttest('get')
    lk_set=1:3;
    optlist = {gsi_ilu_opts,gpcg_ilu_opts,pcg_mean_opts};
else
    lk_set=round(sqrspace(2,20,10));
    optlist = {gsi_std_opts, gsi_dyn_opts, gsi_ilu_opts,...
        gpcg_std_opts, gpcg_dyn_opts, gpcg_ilu_opts, ...
        pcg_mean_opts};
end


for l_k=lk_set
    for def_opts=optlist
        opts{end+1}=varargin2options( [def_opts{1} {'mod_opts', {'l_k',l_k}}] ); 
    end
end













