function show_cmpsol_large_cmp_simple_pcg

% compares performance between tensor pcg and simple iterations

clc

log_start( fullfile( log_file_base(), mfilename ) );
compare_solvers_pcg( 'model_large_easy', get_solve_options )
show_tex_table(1);

global info_tp
for i=1:length(info_tp)
    fprintf( '%10s: ', info_tp{i}.descr);
    fprintf( '%6.4f ', info_tp{i}.resvec);
    fprintf( '\n');
end
log_stop();

function opts=get_solve_options
opts={};
opts{end+1}=struct( 'longdescr', 'PCG', 'descr', 'PCG', 'type', 'pcg');

opts{end+1}=varargin2options( {...
    'longdescr', 'tensor pcg dyn', ...
    'descr', 'tpcg dyn',...
    'type', 'tpcg',...
    'dyn', true ...
    'eps', 1e-6 ...
    'solve', {'upratio_delta', 0.01, 'dyneps_factor', 0.1} } );

opts{end+1}=varargin2options( {...
    'longdescr', 'tensor pcg dyn', ...
    'descr', 'tpcg dyn',...
    'type', 'tpcg',...
    'dyn', true ...
    'eps', 1e-6 ...
    } );

opts{end+1}=varargin2options( {...
    'longdescr', 'tensor pcg', ...
    'descr', 'tpcg',...
    'type', 'tpcg',...
    'eps', 1e-4 ...
    } );


opts{end+1}=varargin2options( {...
    'longdescr', 'tensor pcg6', ...
    'descr', 'tpcg6',...
    'type', 'tpcg',...
    'eps', 1e-6
    } );

opts{end+1}=varargin2options( {...
    'longdescr', 'tensor pcg', ...
    'descr', 'tpcg',...
    'type', 'tpcg',...
    } );

opts{end+1}=varargin2options( {...
    'longdescr', 'tensor dyn', ...
    'descr', 'tensor dyn',...
    'type', 'tensor', ...
    'dyn', true ...
    } );

opts{end+1}=varargin2options( {...
    'longdescr', 'tensor', ...
    'descr', 'tensor',...
    'type', 'tensor', ...
    } );

