function show_cmpsol_large_cmp_simple_pcg

% compares performance between tensor pcg and simple iterations

clc

log_start( fullfile( log_file_base(), mfilename ) );
compare_solvers_pcg( 'model_small_easy', get_solve_options )
show_tex_table(1);
log_stop();

function opts=get_solve_options
opts={};
opts{end+1}=struct( 'longdescr', 'PCG', 'descr', 'PCG', 'type', 'pcg');

opts{end+1}=varargin2options( {...
    'longdescr', 'gpcg', ...
    'descr', 'gpcg',...
    'type', 'gpcg',...
    } );

opts{end+1}=varargin2options( {...
    'longdescr', 'gpcg6', ...
    'descr', 'gpcg6',...
    'type', 'gpcg',...
    'eps', 1e-6
    } );

opts{end+1}=varargin2options( {...
    'longdescr', 'gpcg6 dyn', ...
    'descr', 'gpcg6 dyn',...
    'type', 'gpcg',...
    'dyn', true ...
    'eps', 1e-6 ...
    } );

opts{end+1}=varargin2options( {...
    'longdescr', 'gpcg6 dyn up', ...
    'descr', 'gpcg6 dyn up',...
    'type', 'gpcg',...
    'dyn', true ...
    'eps', 1e-6 ...
    'solve', {'upratio_delta', 0.01, 'dyneps_factor', 0.2} } );

opts{end+1}=varargin2options( {...
    'longdescr', 'gss', ...
    'descr', 'gss',...
    'type', 'gss', ...
    } );

opts{end+1}=varargin2options( {...
    'longdescr', 'gss dyn', ...
    'descr', 'gss dyn',...
    'type', 'gss', ...
    'dyn', true ...
    } );


