# Makefile.in generated by automake 1.9.6 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


srcdir = .
top_srcdir = .

pkgdatadir = $(datadir)/sglib-script
pkglibdir = $(libdir)/sglib-script
pkgincludedir = $(includedir)/sglib-script
top_builddir = .
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/Makefile.inc-mfiles \
	$(srcdir)/run_with.in $(srcdir)/sg_path.m.in \
	$(top_srcdir)/configure install-sh missing
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno configure.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES = run_with sg_path.m
SOURCES =
DIST_SOURCES =
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/ezander/projects/stochastics/sglib/trunk/scripts/missing --run aclocal-1.9
AMTAR = ${SHELL} /home/ezander/projects/stochastics/sglib/trunk/scripts/missing --run tar
AUTOCONF = ${SHELL} /home/ezander/projects/stochastics/sglib/trunk/scripts/missing --run autoconf
AUTOHEADER = ${SHELL} /home/ezander/projects/stochastics/sglib/trunk/scripts/missing --run autoheader
AUTOMAKE = ${SHELL} /home/ezander/projects/stochastics/sglib/trunk/scripts/missing --run automake-1.9
AWK = gawk
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"sglib-script\" -DPACKAGE_TARNAME=\"sglib-script\" -DPACKAGE_VERSION=\"0.2\" -DPACKAGE_STRING=\"sglib-script\ 0.2\" -DPACKAGE_BUGREPORT=\"ezander@tu-bs.de\" -DPACKAGE=\"sglib-script\" -DVERSION=\"0.2\" 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/ezander/projects/stochastics/sglib/trunk/scripts/missing --run makeinfo
PACKAGE = sglib-script
PACKAGE_BUGREPORT = ezander@tu-bs.de
PACKAGE_NAME = sglib-script
PACKAGE_STRING = sglib-script 0.2
PACKAGE_TARNAME = sglib-script
PACKAGE_VERSION = 0.2
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 0.2
ac_ct_STRIP = 
am__leading_dot = .
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build_alias = 
datadir = ${prefix}/share
exec_prefix = ${prefix}
host_alias = 
includedir = ${prefix}/include
infodir = ${prefix}/info
install_sh = /home/ezander/projects/stochastics/sglib/trunk/scripts/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
mkdir_p = mkdir -p --
oldincludedir = /usr/include
prefix = /usr/local
program_transform_name = s,x,x,
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target_alias = 
EXTRA_DIST = \
	mkincmfiles \
	mkprivate \
	$(MFILES)

MFILES = \
	beta_cdf.m\
	beta_moments.m\
	beta_pdf.m\
	beta_stdnor.m\
	Contents.m\
	covariance_matrix.m\
	cross_correlation.m\
	data_moments.m\
	exponential_cdf.m\
	exponential_covariance.m\
	exponential_moments.m\
	exponential_pdf.m\
	exponential_stdnor.m\
	gauss_hermite.m\
	gauss_hermite_multi.m\
	gauss_hermite_rule.m\
	gaussian_covariance.m\
	gauss_legendre_rule.m\
	gauss_legendre_triangle_rule.m\
	hermite.m\
	hermite_norm.m\
	hermite_triple_fast.m\
	hermite_triple_product.m\
	hermite_val.m\
	hermite_val_multi.m\
	inv_reg_beta.m\
	kernel_density.m\
	kl_expand.m\
	kl_pce_field_realization.m\
	lognorm_cdf.m\
	lognorm_moments.m\
	lognorm_pdf.m\
	lognorm_stdnor.m\
	multiindex_combine.m\
	multiindex_factorial.m\
	multiindex.m\
	multiindex_order.m\
	normal_cdf.m\
	normalize_pce.m\
	normal_moments.m\
	normal_pdf.m\
	normal_stdnor.m\
	pce_cdf.m\
	pce_covariance.m\
	pce_expand_1d.m\
	pce_expand_1d_mc.m\
	pce_field_realization.m\
	pce_moments.m\
	pce_pdf.m\
	pce_to_kl.m\
	pce_transform_multi.m\
	plot_field.m\
	spherical_covariance.m\
	test_covariance.m\
	test_cross_correlation.m\
	test_distributions.m\
	test_exponential_covariance.m\
	test_format_poly.m\
	test_gauss_hermite.m\
	test_gaussian_covariance.m\
	test_gauss_legendre.m\
	test_hermite.m\
	test_hermite_triples.m\
	test_hermite_val.m\
	test_hermite_val_multi.m\
	test_inv_reg_beta.m\
	test_kl_expand.m\
	test_mass_matrix.m\
	test_moments.m\
	test_multiindex.m\
	test_normalize_pce.m\
	test_pce_expand_1d.m\
	test_pce_moments.m\
	test_pce_to_kl.m\
	test_row_col_mult.m\
	test_stiffness.m\
	testsuite.m\
	test_utils.m\
	transform_covariance_pce.m\
	uniform_cdf.m\
	uniform_moments.m\
	uniform_pdf.m\
	uniform_stdnor.m\
	experimental/apply_stochastic_operator.m\
	experimental/distribution_object.m\
	experimental/expand_field_kl_pce_hgm.m\
	experimental/idea_structure_coeffs.m\
	experimental/kl_expand_fft.m\
	experimental/orthpol_info.m\
	experimental/orthpol.m\
	experimental/pce_expand_2d.m\
	experimental/test_orth2.m\
	experimental/test_orthpol.m\
	experimental/tp_add.m\
	experimental/tp_create.m\
	experimental/tp_mult.m\
	experimental/tp_reduce.m\
	experimental/tp_subtract.m\
	munit/assert_equals.m\
	munit/assert_false.m\
	munit/assert.m\
	munit/assert_print_module_stats.m\
	munit/assert_reset_options.m\
	munit/assert_run_testsuite.m\
	munit/assert_set_debug.m\
	munit/assert_set_function.m\
	munit/assert_set_module.m\
	munit/assert_set_option.m\
	munit/assert_true.m\
	munit/Contents.m\
	private/assert_equals.m\
	private/assert_false.m\
	private/assert.m\
	private/assert_print_module_stats.m\
	private/assert_reset_options.m\
	private/assert_run_testsuite.m\
	private/assert_set_debug.m\
	private/assert_set_function.m\
	private/assert_set_module.m\
	private/assert_set_option.m\
	private/assert_true.m\
	private/Contents.m\
	private/correct_mesh.m\
	private/edit_mfile.m\
	private/format_poly.m\
	private/funcall.m\
	private/get_option.m\
	private/isfunction.m\
	private/ismatlab.m\
	private/isoctave.m\
	private/isversion.m\
	private/mass_matrix.m\
	private/merge_cells.m\
	private/refine_mesh.m\
	private/row_col_mult.m\
	private/sort_triple.m\
	private/stiffness_matrix.m\
	private/varargin2options.m\
	simplefem/correct_mesh.m\
	simplefem/mass_matrix.m\
	simplefem/refine_mesh.m\
	simplefem/stiffness_matrix.m\
	util/edit_mfile.m\
	util/format_poly.m\
	util/funcall.m\
	util/get_option.m\
	util/isfunction.m\
	util/ismatlab.m\
	util/isoctave.m\
	util/isversion.m\
	util/merge_cells.m\
	util/row_col_mult.m\
	util/sort_triple.m\
	util/varargin2options.m

all: all-am

.SUFFIXES:
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(srcdir)/Makefile.inc-mfiles $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign '; \
	      cd $(srcdir) && $(AUTOMAKE) --foreign  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --foreign  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
run_with: $(top_builddir)/config.status $(srcdir)/run_with.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
sg_path.m: $(top_builddir)/config.status $(srcdir)/sg_path.m.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
uninstall-info-am:
tags: TAGS
TAGS:

ctags: CTAGS
CTAGS:


distdir: $(DISTFILES)
	$(am__remove_distdir)
	mkdir $(distdir)
	$(mkdir_p) $(distdir)/. $(distdir)/experimental $(distdir)/munit $(distdir)/private $(distdir)/simplefem $(distdir)/util
	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
	list='$(DISTFILES)'; for file in $$list; do \
	  case $$file in \
	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
	  esac; \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkdir_p) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(SHELL) $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e '1{h;s/./=/g;p;x;}' -e '$${p;x;}'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile
installdirs:
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f Makefile
distclean-am: clean-am distclean-generic

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am:

install-exec-am:

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-info-am

.PHONY: all all-am am--refresh check check-am clean clean-generic dist \
	dist-all dist-bzip2 dist-gzip dist-shar dist-tarZ dist-zip \
	distcheck distclean distclean-generic distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am install-exec \
	install-exec-am install-info install-info-am install-man \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-generic pdf pdf-am ps ps-am uninstall uninstall-am \
	uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
