#! /bin/bash

{ 
    cat<<EOF
\documentclass{article}
\usepackage{graphicx}
\begin{document}
EOF


    for i in eps/*.eps; do 
	j=$(echo $i|cut -d. -f1); 
	echo "\includegraphics[width=.8 \textwidth]{$j}"
	echo
    done
    
    cat<<EOF
\end{document}
EOF
}>all.tex

latex all.tex
dvips all 
ps2pdf all.ps 
rm all.{tex,ps,log,aux,dvi}
